### ISSUE TITLE
Secure profile fails during gateway setup

### ISSUE THREAD

**Issue by Parth-Brahmbhatt** [hortonworks/structor#6]
I performed the following actions 
ln -s profiles/3node-secure.profile current.profile
mkdir generated
vagrant up

getting following error 
==> gw: Error: openssl req -new -x509 -days 36525 -key ca.key -out ca.crt < /vagrant/modules/ssl_ca/files/ca-info.txt returned 1 instead of one of [0]
==> gw: Error: /Stage[main]/Ssl_ca/Exec[openssl req -new -x509 -days 36525 -key ca.key -out ca.crt < /vagrant/modules/ssl_ca/files/ca-info.txt]/returns: change from notrun to 0 failed: openssl req -new -x509 -days 36525 -key ca.key -out ca.crt < /vagrant/modules/ssl_ca/files/ca-info.txt returned 1 instead of one of [0]

sshing into the host and executing the command manually 
HW10960:structor pbrahmbhatt$ vagrant ssh gw
Loading profile /Users/pbrahmbhatt/repo/structor/profiles/3node-secure.profile
Last login: Tue Apr 15 04:44:58 2014 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
[vagrant@gw ~]$ openssl req -new -x509 -days 36525 -key ca.key -out ca.crt < /vagrant/modules/ssl_ca/files/ca-info.txt
Error opening Private Key ca.key
139978142771016:error:02001002:system library:fopen:No such file or directory:bss_file.c:398:fopen('ca.key','r')
139978142771016:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:400:
unable to load Private Key

**Comment by omalley** [comment]
I found and fixed this one as part of 7fa3b2138.
